# Generated by Django 5.2.10 on 2026-02-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_loginattempt_usersession_trusteddevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitra',
            name='bank_account_holder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mitra',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mitra',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mitra',
            name='ewallet_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mitra',
            name='ewallet_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
