# Generated by Django 5.2.10 on 2026-02-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_mitra_bank_account_holder_mitra_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitra',
            name='google_sheet_id',
            field=models.CharField(blank=True, help_text="ID of the Google Sheet for this Mitra's daily report", max_length=100, null=True),
        ),
    ]
