# Generated by Django 5.2.10 on 2026-02-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_mitra_google_sheet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitra',
            name='qris_image',
            field=models.ImageField(blank=True, null=True, upload_to='qris/'),
        ),
    ]
