# Generated by Django 5.2.10 on 2026-02-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_mitra_qris_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitra',
            name='qris_data',
            field=models.TextField(blank=True, help_text='Data string dari statis QRIS untuk digenerate menjadi dinamis', null=True),
        ),
    ]
