# Generated by Django 5.2.10 on 2026-01-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Deskripsi menu, contoh: 1 Pc Ayam + Nasi + Es Teh', null=True),
        ),
    ]
