# Generated by Django 5.2.10 on 2026-02-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_set_default_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, help_text='Tailwind color identifier (e.g., orange, blue, purple)', max_length=50, null=True),
        ),
    ]
