# Generated by Django 5.2.10 on 2026-02-16 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_modifiergroup_modifieroption_productvariant'),
        ('users', '0006_loginattempt_usersession_trusteddevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifierAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mitra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_availabilities', to='users.mitra')),
                ('modifier_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitra_availabilities', to='catalog.modifieroption')),
            ],
            options={
                'verbose_name_plural': 'Modifier Availabilities',
                'unique_together': {('mitra', 'modifier_option')},
            },
        ),
        migrations.CreateModel(
            name='ProductAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mitra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_availabilities', to='users.mitra')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitra_availabilities', to='catalog.product')),
            ],
            options={
                'verbose_name_plural': 'Product Availabilities',
                'unique_together': {('mitra', 'product')},
            },
        ),
    ]
