# Generated by Django 5.2.10 on 2026-02-16 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_modifieravailability_productavailability'),
        ('inventory', '0005_stocklog_mitra_ingredientstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifieroption',
            name='ingredient',
            field=models.ForeignKey(blank=True, help_text='Ingredient used for this modifier (e.g., Keju -> Keju Block)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifier_options', to='inventory.ingredient'),
        ),
        migrations.AddField(
            model_name='modifieroption',
            name='quantity_required',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount of ingredient used per selection', max_digits=10),
        ),
    ]
