# Generated by Django 5.2.10 on 2026-01-29 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(choices=[('gram', 'Gram'), ('ml', 'Milliliter'), ('pcs', 'Pieces'), ('kg', 'Kilogram'), ('liter', 'Liter')], default='gram', max_length=20)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, help_text='Current stock in the specified unit', max_digits=10)),
                ('min_stock_alert', models.DecimalField(decimal_places=2, default=0, help_text='Alert threshold', max_digits=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Instructions or notes for this recipe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(help_text='Only products that do not track inventory (Racikan) can have a recipe.', limit_choices_to={'track_inventory': False}, on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_stock', models.DecimalField(decimal_places=2, help_text='Stock level after change', max_digits=10)),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In (Purchase/Adjustment)'), ('OUT', 'Stock Out (Sales/Damage)')], max_length=10)),
                ('reason', models.CharField(choices=[('SALES', 'Sales'), ('PURCHASE', 'Purchase'), ('ADJUSTMENT', 'Manual Adjustment'), ('WASTE', 'Waste/Spoilage')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, help_text='User/System who initiated', max_length=100)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='inventory.ingredient')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_logs', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=2, help_text='Amount required per 1 unit of Product', max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_recipes', to='inventory.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.recipe')),
            ],
            options={
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
    ]
