# Generated by Django 5.2.10 on 2026-02-15 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestockOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Pembayaran'), ('PAID', 'Dibayar'), ('PREPARING', 'Disiapkan'), ('SHIPPED', 'Dikirim'), ('RECEIVED', 'Diterima'), ('CANCELLED', 'Dibatalkan')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(choices=[('TRANSFER', 'Transfer Bank'), ('DANA', 'DANA'), ('GOPAY', 'GoPay'), ('SHOPEEPAY', 'ShopeePay'), ('OVO', 'OVO')], default='TRANSFER', max_length=20)),
                ('shipping_address', models.TextField(blank=True, help_text='Alamat pengiriman Mitra')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('preparing_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('external_order_id', models.CharField(blank=True, help_text='ID from samdenidimsum system', max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestockOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(help_text='Unit snapshot from ingredient', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Harga per unit dari HQ', max_digits=12)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restock_items', to='inventory.ingredient')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.restockorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
