# Generated by Django 5.2.10 on 2026-02-15 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_restockorder_restockorderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_code', models.CharField(editable=False, max_length=30, unique=True)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('payment_proof_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='Payment must be made before this time')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Menunggu Bukti'), ('PROCESSING', 'Memverifikasi'), ('VERIFIED', 'Terverifikasi'), ('REJECTED', 'Ditolak'), ('MANUAL_REVIEW', 'Perlu Review Manual'), ('EXPIRED', 'Kedaluwarsa')], default='PENDING', max_length=20)),
                ('verification_result', models.JSONField(blank=True, default=dict, help_text='AI analysis result')),
                ('verification_confidence', models.IntegerField(default=0, help_text='AI confidence 0-100%')),
                ('rejection_reason', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='inventory.restockorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
