# Generated by Django 5.2.10 on 2026-02-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restockorder',
            name='payment_method',
            field=models.CharField(choices=[('TRANSFER', 'Transfer Bank'), ('QRIS', 'QRIS'), ('VA', 'Virtual Account'), ('DANA', 'DANA'), ('GOPAY', 'GoPay'), ('SHOPEEPAY', 'ShopeePay'), ('OVO', 'OVO')], default='TRANSFER', max_length=20),
        ),
    ]
