# Generated by Django 5.2.10 on 2026-02-16 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_restockorder_payment_method'),
        ('users', '0006_loginattempt_usersession_trusteddevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklog',
            name='mitra',
            field=models.ForeignKey(blank=True, help_text='Mitra who owns this stock movement. Null for HQ/Global.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_logs', to='users.mitra'),
        ),
        migrations.CreateModel(
            name='IngredientStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, help_text='Current stock for this Mitra', max_digits=10)),
                ('min_stock_alert', models.DecimalField(decimal_places=2, default=0, help_text='Alert threshold for this Mitra', max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitra_stocks', to='inventory.ingredient')),
                ('mitra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_stocks', to='users.mitra')),
            ],
            options={
                'verbose_name_plural': 'Ingredient Stocks',
                'unique_together': {('mitra', 'ingredient')},
            },
        ),
    ]
