# Generated by Django 5.2.10 on 2026-02-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stocklog_mitra_ingredientstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Harga beli per unit (Rp). Digunakan untuk kalkulasi HPP.', max_digits=12),
        ),
    ]
