# Generated by Django 5.2.10 on 2026-02-19 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_ingredient_cost_per_unit'),
        ('users', '0008_mitra_google_sheet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='restockorder',
            name='mitra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restock_orders', to='users.mitra'),
        ),
        migrations.AddField(
            model_name='restockorder',
            name='receiving_proof',
            field=models.ImageField(blank=True, null=True, upload_to='receiving_proofs/'),
        ),
    ]
