# Generated by Django 5.2.10 on 2026-02-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account', models.CharField(blank=True, max_length=100)),
                ('bank_holder', models.CharField(blank=True, max_length=100)),
                ('dana_number', models.CharField(blank=True, max_length=20)),
                ('gopay_number', models.CharField(blank=True, max_length=20)),
                ('shopeepay_number', models.CharField(blank=True, max_length=20)),
                ('ovo_number', models.CharField(blank=True, max_length=20)),
                ('qris_image', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
