# Generated by Django 5.2.10 on 2026-02-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='qris_data',
            field=models.TextField(blank=True, help_text='Raw QRIS EMVCo data string for dynamic QR generation. Get this by scanning your static QRIS with any QR reader.'),
        ),
    ]
