# Generated by Django 5.2.10 on 2026-02-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_storesettings_qris_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeederLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('checksum', models.CharField(help_text='SHA256 checksum of the seed file', max_length=64)),
                ('executed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
