# Generated by Django 5.2.10 on 2026-02-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seederlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='spreadsheet_url',
            field=models.URLField(blank=True, help_text='Link to external summary spreadsheet', null=True),
        ),
    ]
