# Generated by Django 5.2.10 on 2026-02-16 05:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0004_orderitem_modifiers_snapshot_and_more'),
        ('users', '0006_loginattempt_usersession_trusteddevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(help_text='Jumlah pengeluaran dalam Rupiah')),
                ('category', models.CharField(choices=[('GAS', 'Gas LPG'), ('BAHAN_DARURAT', 'Bahan Baku Darurat'), ('PACKAGING', 'Kemasan & Packaging'), ('TRANSPORT', 'Transportasi'), ('MAINTENANCE', 'Perawatan Alat'), ('LAINNYA', 'Lainnya')], default='LAINNYA', max_length=20)),
                ('description', models.CharField(help_text='Deskripsi singkat pengeluaran', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Catatan tambahan (opsional)', null=True)),
                ('proof_image', models.ImageField(blank=True, help_text='Foto bukti pengeluaran (struk/nota)', null=True, upload_to='expenses/proofs/')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Tanggal pengeluaran')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mitra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='users.mitra')),
                ('shift', models.ForeignKey(blank=True, help_text='Shift saat pengeluaran dicatat (opsional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='sales.shift')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
