# Generated by Django 5.2.10 on 2026-02-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_shift_order_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='modifiers_snapshot',
            field=models.JSONField(blank=True, help_text='Snapshot of selected modifiers', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_snapshot',
            field=models.JSONField(blank=True, help_text='Snapshot of selected variant', null=True),
        ),
    ]
